apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/argo-events
    repoURL: git@github.com:sebastiaankok/argocd-applications.git
    targetRevision: HEAD
