apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  destination:
    namespace: tekton-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/tekton
    repoURL: git@github.com:sebastiaankok/argocd-applications.git
    targetRevision: HEAD
